[build]
  command = "bun install && bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  # Exclude build artifacts from secrets scanning to prevent false positives
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**,node_modules/**,bun.lockb,package-lock.json"
  SECRETS_SCAN_OMIT_KEYS = "STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/ar/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Secrets scanning configuration - be permissive during deployment
[context.production.environment]
  SECRETS_SCAN_ENABLED = "true"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**,node_modules/**,bun.lockb,package-lock.json"
  SECRETS_SCAN_OMIT_KEYS = "STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET"

[context.deploy-preview.environment]
  SECRETS_SCAN_ENABLED = "true"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**,node_modules/**,bun.lockb,package-lock.json"
  SECRETS_SCAN_OMIT_KEYS = "STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET"
